# Generated by Django 2.1.5 on 2019-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupper',
            name='aggregate_score',
            field=models.IntegerField(default=0),
        ),
    ]
